# Generated by Django 6.1.1 on 2026-09-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='events/banners/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PUBLISHED', 'منتشر شده'), ('REGISTRATION_CLOSED', 'بسته شدن ثبت\u200cنام'), ('FINISHED', 'پایان یافته'), ('CANCELLED', 'لغو شده')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='eventstage',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='ظرفیت اختصاصی مرحله', null=True),
        ),
        migrations.AlterField(
            model_name='eventstage',
            name='stage_roles',
            field=models.CharField(blank=True, default='', help_text='سخنرانان، داوران یا مربیان این مرحله', max_length=255),
        ),
    ]
