# Generated by Django 5.2.17 on 2026-09-06 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_banner_alter_event_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventresult',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventstage',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='eventstage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='banner',
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='برگزارکننده'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Draft', 'پیش\u200cنویس'), ('Published', 'منتشر شده'), ('Closed', 'ثبت\u200cنام بسته شده'), ('Finished', 'به پایان رسیده'), ('Cancelled', 'لغو شده')], default='Draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان رویداد'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.event', verbose_name='رویداد'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_results', to=settings.AUTH_USER_MODEL, verbose_name='شرکت\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات و بازخورد داور'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='eventstage',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ظرفیت مرحله'),
        ),
        migrations.AlterField(
            model_name='eventstage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='eventstage',
            name='end_time',
            field=models.DateTimeField(verbose_name='زمان پایان مرحله'),
        ),
        migrations.AlterField(
            model_name='eventstage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='events.event', verbose_name='رویداد'),
        ),
        migrations.AlterField(
            model_name='eventstage',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='eventstage',
            name='stage_roles',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نقش\u200cهای مرحله (سخنران/داور)'),
        ),
        migrations.AlterField(
            model_name='eventstage',
            name='start_time',
            field=models.DateTimeField(verbose_name='زمان شروع مرحله'),
        ),
        migrations.AlterField(
            model_name='eventstage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان مرحله'),
        ),
        migrations.AlterUniqueTogether(
            name='eventresult',
            unique_together={('event', 'participant')},
        ),
    ]
