# Generated by Django 6.1.1 on 2026-09-06 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('FLOAT', 'Float')], default='TEXT', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=500, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_values', to='attributes.attribute')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'attribute')},
            },
        ),
    ]
